"""Authority-preserving cross-domain context contracts.

The package is read-only with respect to native domain engines. It exposes common
fact references, causal/correlation metadata, thin domain read projections,
qualified location views, context axes and scoped permission. BUY/SELL and action
authority remain outside this package.
"""

from .axes import (
    AxisReason,
    ConflictState,
    ContextAxes,
    ContextDirection,
    ContinuationContext,
    HamReadinessContext,
    MTFContext,
    ObjectiveContext,
    ParticipationContext,
    PatternReadiness,
    ReactionContext,
    ReversalContext,
    StructuralThesis,
    VolatilityContext,
    evaluate_context_axes,
)
from .builder import CrossDomainBuildInputs, CrossDomainBuildResult, build_cross_domain_context
from .envelope import (
    CausalFamily,
    ContextDataQuality,
    ContextDomain,
    FactRef,
    SourceFamily,
    normalize_context_data_quality,
)
from .lineage import (
    LineageGroup,
    build_lineage_groups,
    families_for,
    known_independent_origin_count,
    lineage_id_from_origin_event,
    unknown_lineage_refs,
)
from .permissions import (
    GateState,
    PermissionEnvelope,
    PermissionScope,
    PermittedSide,
    resolve_permission,
)
from .projections import (
    HamProjection,
    LiquidityProjection,
    ParticipationProjection,
    PatternProjection,
    ReactionEvidenceProjection,
    StabilSupportProjection,
    StructuralFactsProjection,
    VolatilityProjection,
    project_ham,
    project_liquidity,
    project_participation,
    project_pattern,
    project_reaction_evidence,
    project_stabil_support,
    project_structural_facts,
    project_volatility,
)
from .snapshot import (
    CrossDomainContextSnapshot,
    KnowledgeBoundary,
    build_context_snapshot,
    eligible_fact_refs,
    evaluate_knowledge_boundary,
)
from .zone_interaction import (
    ZoneInteractionEvent,
    ZoneInteractionState,
    classify_zone_interaction,
    interval_distance,
    price_position,
    transition_event,
)
from .zones import (
    QualifiedZone,
    QualifiedZoneSide,
    StructuralZoneRef,
    ZoneAnchorKind,
    ZoneFreshness,
    ZoneIntelligenceConfig,
    ZoneIntelligenceSnapshot,
    ZoneQualification,
    ZoneRelevance,
    build_zone_intelligence,
)

__all__ = [
    "AxisReason",
    "CausalFamily",
    "ConflictState",
    "ContextAxes",
    "ContextDataQuality",
    "ContextDirection",
    "ContextDomain",
    "ContinuationContext",
    "CrossDomainBuildInputs",
    "CrossDomainBuildResult",
    "CrossDomainContextSnapshot",
    "FactRef",
    "GateState",
    "HamProjection",
    "HamReadinessContext",
    "KnowledgeBoundary",
    "LineageGroup",
    "LiquidityProjection",
    "MTFContext",
    "ObjectiveContext",
    "ParticipationContext",
    "ParticipationProjection",
    "PatternProjection",
    "PatternReadiness",
    "PermissionEnvelope",
    "PermissionScope",
    "PermittedSide",
    "QualifiedZone",
    "QualifiedZoneSide",
    "ReactionContext",
    "ReactionEvidenceProjection",
    "ReversalContext",
    "SourceFamily",
    "StabilSupportProjection",
    "StructuralFactsProjection",
    "StructuralThesis",
    "StructuralZoneRef",
    "VolatilityContext",
    "VolatilityProjection",
    "ZoneAnchorKind",
    "ZoneFreshness",
    "ZoneIntelligenceConfig",
    "ZoneIntelligenceSnapshot",
    "ZoneInteractionEvent",
    "ZoneInteractionState",
    "ZoneQualification",
    "ZoneRelevance",
    "build_context_snapshot",
    "build_cross_domain_context",
    "build_lineage_groups",
    "build_zone_intelligence",
    "classify_zone_interaction",
    "eligible_fact_refs",
    "evaluate_context_axes",
    "evaluate_knowledge_boundary",
    "families_for",
    "interval_distance",
    "known_independent_origin_count",
    "lineage_id_from_origin_event",
    "normalize_context_data_quality",
    "price_position",
    "project_ham",
    "project_liquidity",
    "project_participation",
    "project_pattern",
    "project_reaction_evidence",
    "project_stabil_support",
    "project_structural_facts",
    "project_volatility",
    "resolve_permission",
    "transition_event",
    "unknown_lineage_refs",
]
